import { ServerBuild } from '@remix-run/cloudflare'
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as serverBuild from '../build/server'
import { getLoadContext } from '../load-context'

// TODO: passing build directly causing typescript error
const build = serverBuild as unknown as ServerBuild

export const onRequest = createPagesFunctionHandler<Env>({
  build,
  mode: process.env.NODE_ENV,
  getLoadContext,
})
