#:schema node_modules/wrangler/config-schema.json
name = "fem-notes"
compatibility_date = "2024-11-12"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "fem-notes"
database_id = "ebc59c64-28b1-4f34-a1aa-6048027581ab"
migrations_dir = "app/db/migrations"
preview_database_id = "DB"
