// Generated by Wrangler by running `wrangler types types/worker-configuration.d.ts`

interface Env {
  CLOUDFLARE_ACCOUNT_ID: string
  CLOUDFLARE_DATABASE_ID: string
  CLOUDFLARE_D1_TOKEN: string
  NODE_ENV: string
  TOTP_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  RESEND_API_KEY: string
  SUPPORT_EMAIL: string
  DB: D1Database
}
