name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          wranglerVersion: "3.57.1"
          preCommands: |
            pnpm install
            pnpm run build
          command: pages deploy --project-name=fem-notes
